@echo off
REM Super Agent Self-Upgrading System - Quick Setup
REM Run this script to set up the complete infrastructure

setlocal

echo ================================================
echo  SUPER AGENT SELF-UPGRADING SYSTEM SETUP
echo ================================================
echo.

REM ================================================
REM CONFIGURATION
REM ================================================
set SUPABASE_URL=https://your-project.supabase.co
set SUPABASE_SERVICE_KEY=your-service-key
set GITHUB_TOKEN=your-github-token
set REPO_OWNER=aimerdoux
set REPO_NAME=super-agent-architecture

REM ================================================
REM CHECK PREREQUISITES
REM ================================================
echo [1/6] Checking prerequisites...

where git >nul 2>&1
if %errorlevel% neq 0 (
    echo ❌ Git not found. Please install Git first.
    exit /b 1
)
echo ✅ Git found

where node >nul 2>&1
if %errorlevel% neq 0 (
    echo ❌ Node.js not found. Please install Node.js 22+ first.
    exit /b 1
)
for /f "tokens=*" %%i in ('node -v') do set NODE_VERSION=%%i
echo ✅ Node.js found: %NODE_VERSION%

echo.
REM ================================================
REM CREATE SUPABASE PROJECT
REM ================================================
echo [2/6] Supabase Setup

set /p SUPABASE_URL="Enter your Supabase Project URL (or press Enter to skip): "
if "%SUPABASE_URL%"=="" (
    echo ⏭️  Skipping Supabase setup
    goto :SKIP_SUPABASE
)

echo Creating database schema...
REM Note: Run supabase\schema.sql in your Supabase SQL Editor
echo.
echo 📋 Please do the following in Supabase Dashboard:
echo    1. Go to SQL Editor
echo    2. Copy and run the contents of: supabase\schema.sql
echo    3. Copy the Service Role Key to .env file
echo.
echo ⚠️  This script does NOT execute SQL directly for safety.
echo.

:SKIP_SUPABASE

REM ================================================
REM CONFIGURE ENVIRONMENT
REM ================================================
echo [3/6] Creating environment configuration...

set CONFIG_FILE=.env
(
    echo # Super Agent Configuration
    echo # Generated by setup.bat
    echo.
    echo SUPABASE_URL=%SUPABASE_URL%
    echo SUPABASE_SERVICE_KEY=%SUPABASE_SERVICE_KEY%
    echo GITHUB_TOKEN=%GITHUB_TOKEN%
    echo REPO_OWNER=%REPO_OWNER%
    echo REPO_NAME=%REPO_NAME%
    echo.
    echo # OpenClaw
    echo OPENCLAW_Workspace=%cd%
) > %CONFIG_FILE%

echo ✅ Created %CONFIG_FILE%
echo ⚠️  Please update %CONFIG_FILE% with your actual API keys

REM ================================================
REM SETUP GITHUB SECRETS
REM ================================================
echo [4/6] GitHub Secrets

echo.
echo 📋 To enable auto-deploy, add these secrets to GitHub:
echo.
echo    1. Go to your repository: https://github.com/%REPO_OWNER%/%REPO_NAME%/settings/secrets/actions
echo    2. Add the following secrets:
echo.
echo    ┌─────────────────────────────┬──────────────────────────────────┐
echo    │ Secret Name                 │ Value                            │
echo    ├─────────────────────────────┼──────────────────────────────────┤
echo    │ SUPABASE_PROJECT_REF        │ Your Supabase project ID         │
echo    │ SUPABASE_ACCESS_TOKEN       │ Supabase CLI access token        │
echo    │ SUPABASE_SERVICE_KEY        │ Supabase service role key        │
echo    │ GITHUB_TOKEN                │ GitHub PAT with repo scope       │
echo    └─────────────────────────────┴──────────────────────────────────┘
echo.

set /p CONFIRM="Have you added the secrets? (y/n): "
if not "%CONFIRM%"=="y" (
    echo ⚠️  Please add secrets before running deployments
)

REM ================================================
REM DEPLOY EDGE FUNCTIONS (if CLI available)
REM ================================================
echo [5/6] Deploy Edge Functions

where npx >nul 2>&1
if %errorlevel% neq 0 (
    echo ❌ npx not found. Please install Node.js first.
    goto :SKIP_FUNCTIONS
)

set /p DEPLOY="Deploy Edge Functions now? (y/n): "
if "%DEPLOY%"=="y" (
    echo.
    echo 🚀 Deploying Edge Functions...
    echo.
    
    if exist "supabase\functions\self-upgrade" (
        echo 📦 Deploying self-upgrade function...
        npx supabase functions deploy self-upgrade --project-ref %SUPABASE_PROJECT_REF%
    )
    
    if exist "supabase\functions\agent-core" (
        echo 📦 Deploying agent-core function...
        npx supabase functions deploy agent-core --project-ref %SUPABASE_PROJECT_REF%
    )
    
    echo ✅ Edge Functions deployed
) else (
    echo ⏭️  Skipping Edge Function deployment
)

:SKIP_FUNCTIONS

REM ================================================
REM FINAL SETUP
REM ================================================
echo [6/6] Final Configuration

echo.
echo ✅ Setup Complete!
echo.
echo ================================================
echo  NEXT STEPS
echo ================================================
echo.
echo 1. 📝 Update .env file with your actual API keys
echo.
echo 2. 🔐 Add GitHub secrets (if not done):
echo    supabase functions generate secret SUPABASE_ACCESS_TOKEN
echo    supabase functions generate secret SUPABASE_SERVICE_KEY
echo.
echo 3. 🗄️  Run schema.sql in Supabase SQL Editor
echo.
echo 4. 🚀 Push to GitHub to trigger first deployment:
echo    git add .
echo    git commit -m "Initial self-upgrading agent"
echo    git push origin main
echo.
echo 5. 📖 Read the full documentation:
echo    self-upgrading-agent.md
echo.
echo ================================================
echo  QUICK COMMANDS
echo ================================================
echo.
echo Check agent status:
echo   curl https://your-project.functions.supabase.co/agent-core ^
echo     -H "Authorization: Bearer YOUR_KEY" ^
echo     -H "Content-Type: application/json" ^
echo     -d "{\"action\": \"status\"}"
echo.
echo Trigger self-upgrade:
echo   curl https://your-project.functions.supabase.co/self-upgrade ^
echo     -H "Authorization: Bearer YOUR_KEY" ^
echo     -H "Content-Type: application/json" ^
echo     -d "{\"action\": \"pull\"}"
echo.
echo ================================================

endlocal
pause
